version: '3.8'

services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.2
    restart: always
    depends_on:
      - redis
      - postgres
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080 # Expor para o Caddy acessar internamente

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - evolution-net
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    expose:
      - 6379 # Expor a porta correta internamente para outros serviços

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    environment:
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432 # Expor internamente para outros serviços

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"       # Porta HTTP
      - "443:443"     # Porta HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
